spring:
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8855"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console.enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 9000

management:
  info.env.enabled: true
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: '*'

  tracing:
    enabled: true
    sampling.probability: 1.0
  metrics.distribution.percentiles-histogram.http.server.requests: true
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

endpoints.shutdown.enabled: true

info:
  app:
    name: Cards microservice
    description: DemoBank Cards app
    version: 1.0.0

logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    denis.nesterov.demo.microservices.cards: DEBUG
