version: "3.8"

networks:
  demobank-network:

services:
  configuration:
    image: bank_demo/configuration:latest
    ports:
      - "8855:8855"
    networks:
      - demobank-network

  accounts:
    depends_on:
      - configuration
    image: bank_demo/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855

  cards:
    depends_on:
      - configuration
    image: bank_demo/cards:latest
    ports:
      - "9000:9000"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855

  loans:
    depends_on:
      - configuration
    image: bank_demo/loans:latest
    ports:
      - "8090:8090"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855

