spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8855"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # auto-detection and building routes via services names
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 6060

management:
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

endpoints:
  shutdown:
    enabled: false

info:
  app:
    name: Gateway microservice
    description: DemoBank Gateway app
    version: 1.0.0
