
deploymentName: loans-service-deployment
deploymentLabel: loans-service

replicaCount: 1

image:
  repository: asia.gcr.io/bank-demo-383910/bank_demo/loans
  tag: latest

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

autoscaling:
  hpa:
    enabled: true
    name: loans-service-hpa
    deploymentName: loans-service-deployment
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 50

iam_enabled: false
profile_enabled: true
config_enabled: true
zipkin_enabled: true
eureka_enabled: true
