apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service-deployment
  labels:
    app: log-service-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service-label
  template:
    metadata:
      labels:
        app: log-service-label
    spec:
      containers:
        - name: zipkin-container
          image: openzipkin/zipkin:2.24
          ports:
            - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: log-service-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
