apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
  labels:
    app: discovery-service-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service-label
  template:
    metadata:
      labels:
        app: discovery-service-label
    spec:
      containers:
        - name: discovery-service-container
          image: bank_demo/discovery:latest
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SPRING_CONFIG_IMPORT
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
