apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-deployment
  labels:
    app: accounts-service-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service-label
  template:
    metadata:
      labels:
        app: accounts-service-label
    spec:
      containers:
        - name: accounts-service-container
          image: bank_demo/accounts:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SPRING_CONFIG_IMPORT
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts-service-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
