version: "3.8"

networks:
  demobank-network:

services:
  configuration:
    image: bank_demo/configuration:latest
    ports:
      - "8855:8855"
    networks:
      - demobank-network

  discovery:
    image: bank_demo/discovery:latest
    depends_on:
      - configuration
    ports:
      - "8070:8070"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855

  gateway:
    image: bank_demo/gateway:latest
    depends_on:
      - configuration
      - discovery
    ports:
      - "6060:6060"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8070/eureka

  accounts:
    image: bank_demo/accounts:latest
    depends_on:
      - configuration
      - discovery
    ports:
      - "8080:8080"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8070/eureka

  cards:
    image: bank_demo/cards:latest
    depends_on:
      - configuration
      - discovery
    ports:
      - "9000:9000"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8070/eureka

  loans:
    image: bank_demo/loans:latest
    depends_on:
      - configuration
      - discovery
    ports:
      - "8090:8090"
    networks:
      - demobank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:8855
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8070/eureka

