spring:
  application:
    name: "config-service"
  profiles:
#    active: native # native for classpath/filesystem configurations
    active: git # git for configurations from git repository
  cloud:
    config:
      server:
#        native.search-locations: classpath:/configs # classpath
#        native.search-locations: file:///C://configs # filesystem
        git:
          uri: git@bank_demo_configs_host:exelure/bank_demo_configs.git
          passphrase: 12345678 # don't forget to provide pass phrase to unlock your private cert
          clone-on-start: true
          default-label: main
          search-paths:
            - "/defaults"
            - "/env_{profile}/{application}"

server:
  port: 8855

encrypt:
  key: mywordismypassword

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  metrics.distribution.percentiles-histogram.http.server.requests: true
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    denis.nesterov.demo.microservices.configuration: DEBUG
