spring:
  application:
    name: "config-server"
  profiles:
    active: native # native for classpath configurations
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
server:
  port: 8855
