
deploymentName: accounts-service-deployment
deploymentLabel: accounts-service

replicaCount: 1

image:
  repository: asia.gcr.io/bank-demo-383910/bank_demo/accounts
  tag: latest

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
  hpa:
    enabled: true
    name: accounts-service-hpa
    deploymentName: accounts-service-deployment
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 50

iam_enabled: false
profile_enabled: true
config_enabled: true
zipkin_enabled: true
eureka_enabled: true
