
deploymentName: cards-service-deployment
deploymentLabel: cards-service

replicaCount: 1

image:
  repository: asia.gcr.io/bank-demo-383910/bank_demo/cards
  tag: latest

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

autoscaling:
  hpa:
    enabled: true
    name: cards-service-hpa
    deploymentName: cards-service-deployment
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 50

iam_enabled: false
profile_enabled: true
config_enabled: true
zipkin_enabled: true
eureka_enabled: true
