{{- define "common.hpa" -}}
{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.autoscaling.hpa.name }}
  labels:
    app: {{ .Values.autoscaling.hpa.name }}
spec:
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.autoscaling.hpa.deploymentName }}
  metrics:
    {{- if .Values.autoscaling.hpa.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.hpa.cpuUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.memoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.hpa.memoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end -}}
