{{- define "common.hpa" -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name }}
  labels:
    app: {{ .Values.hpa.name }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.hpa.deploymentName }}
  metrics:
    {{- if .Values.autoscaling.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.cpuUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.memoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.memoryUtilizationPercentage }}
    {{- end }}
{{- end -}}
